### PR TITLE
fixes type errors on react-redux connect

### PR DESCRIPTION
**Pull request by sikozonpc**
*Fixes:
 - Bumped `react-redux` and `react-router` versions (connect() was not detecting own props might be related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16990
 but couldnt find any example with our version, also makes possible to removes some of the strong typing there was on the connect)
 - removed `withRouter` from (SideBar and Error)

### CODE REVIEW

**Review by jcreixell — APPROVED** [review]
nice cleanup!

**Comment by jcreixell** [comment]
@sikozonpc BTW I was playing with https://github.com/supasate/connected-react-router last weekend, could be interesting for centralising navigation related state changes, although in order to access the match params seems like it is still necessary to use `withRouter`. I still haven't figured out if there is a better way to synchronise navigation related state with internal app state and avoid the usage of `withRouter`

**Comment by sikozonpc** [comment]
> @sikozonpc BTW I was playing with https://github.com/supasate/connected-react-router ...

@jcreixell  I've used it before, it's pretty cool for debugging and side-effects.
However, as mentioned here https://reacttraining.com/react-router/web/guides/redux-integration it comes with a bit of an overhead for what we might get.

With this, we could access the matched params from `useParams` hook and for other stuff the `useHistory` . The good thing about these hooks is they make the code more declarative without much side-effects.

Altough I don't know what is the scope for client navigation in the future.

**Comment by jcreixell** [comment]
@sikozonpc to your last question, we don't have special plans for navigation, what you propose sounds reasonable. I have done some testing with the router hooks and it works pretty well. I also like the idea of centralising navigation in the container component, meaning only one component needs `withRouter` and route params can be injected in the rest of components via props. That should make components easier to test in the future, and we don't need to use redux for routing at all. In any case, feel free to propose whatever you think is best, i am still learning the right way of doing this

**Pull request merged**
