### PR TITLE
Upgrade bootstrap to v4

### PR DESCRIPTION
**Pull request by jcreixell**
- Adapts the UI to the new version, removing all unnecessary styles
  - Replaces less wth sass (used by new bootstrap version)

image

### CODE REVIEW

**Comment by jcreixell** [comment]
depends on #67 , fixes #38

**Review by rciovati — APPROVED** [review]
web development is not my forte but SGTM 👍

**Comment by jcreixell** [comment]
rebased

**Review by cangoektas — APPROVED** [review]
Looks good!

**Pull request merged**
